services:
  - type: web
    name: ontrack
    env: python
    buildCommand: pip install -r requirements.txt && cd frontend && npm install && npm run build
    startCommand: python main.py
    envVars:
      - key: PORT
        value: 8000
    routes:
      - type: rewrite
        source: /*
        destination: /
