services:
  - type: web
    name: ontrack-v2
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: python main.py
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHON_VERSION
        value: 3.9.0
